apiVersion: v1
kind: Service
metadata:
  name: gitops-secrets-service
spec:
  type: LoadBalancer
  selector:
    app: gitops-secrets-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080